# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    MAKEFILE                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dheredat <dheredat@student.21-school.ru    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/04/12 11:27:08 by dheredat          #+#    #+#              #
#    Updated: 2020/04/12 11:46:37 by dheredat         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = lem_in

LIBFT_DIR =	./ft_printf
SRC_DIR =	./src
INC_DIR =	./inc
OBJ_DIR =	./obj

FLAGS = -Wall -Wextra -Werror
HEAD = $(INC_DIR)/lem_in.h

SRC =	valid.c parser.c transport.c\
		algo_proto.c make_way_proto.c

all: $(NAME)

$(NAME): gcc -g $(SRC_DIR) $(SRC) libftprintf.a -o $(NAME)