#!/bin/bash
maps=`ls maps_big | sort|uniq | tr '\n' ' '`
date > log
echo >> log
for map in $maps
do
echo $map >> log
orig=`cat maps_big/$map | wc -l`
base=`./lem_in < maps_big/$map | wc -l`
base=$((base - orig - 1))
echo $base >> log
tail -1 "maps_big/"$map >> log
echo >> log
done