#!/bin/bash
maps=`ls $1 | sort|uniq | tr '\n' ' '`
date > links.log
echo >> links.log
for map in $maps
do
echo $map >> links.log
orig=`cat $1/$map | wc -l`
base=`./lem-in "$1/$map" | wc -l`
base=$((base - orig - 1))
echo $base >> links.log
tail -1 $1/$map >> links.log
echo >> links.log
done